export const ROLES = {
  FOUNDER: 'Founder',
  DIRECTOR: 'Director',
  COORDINATOR: 'Coordinator',
  SENIOR_PASTOR: 'Senior Pastor',
  ADMIN: 'Admin',
  FINANCE_TEAM: 'Finance Team',
  MINISTRY_LEADER: 'Ministry Leaders',
  OFFICE_SECRETARY: 'Office Secretary',
  VIEWER: 'Viewer',
}

export const ROLE_PERMISSIONS = {
  [ROLES.FOUNDER]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: true,
    manageDepartments: true,
    enterAttendance: true,
    enterFinance: true,
    exportReports: true,
    editSundayPlanFull: true,
    viewDepartmentInsights: true,
    pastorHub: true,
  },
  [ROLES.SENIOR_PASTOR]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: true,
    enterFinance: false,
    exportReports: true,
    editSundayPlanFull: true,
    viewDepartmentInsights: true,
    pastorHub: true,
  },
  [ROLES.DIRECTOR]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: false,
    exportReports: true,
    editSundayPlanFull: true,
    viewDepartmentInsights: true,
  },
  [ROLES.COORDINATOR]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: false,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: true,
    enterFinance: false,
    exportReports: false,
    editSundayPlanFull: false,
    viewDepartmentInsights: false,
  },
  [ROLES.ADMIN]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: false,
    reports: true,
    manageUsers: false,
    manageDepartments: true,
    enterAttendance: true,
    enterFinance: false,
    exportReports: true,
    editSundayPlanFull: true,
    viewDepartmentInsights: true,
  },
  [ROLES.FINANCE_TEAM]: {
    dashboard: true,
    departments: false,
    tasks: false,
    attendance: false,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: true,
    exportReports: true,
    editSundayPlanFull: false,
    viewDepartmentInsights: false,
  },
  [ROLES.MINISTRY_LEADER]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: false,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: true,
    enterFinance: false,
    exportReports: false,
    editSundayPlanFull: false,
    viewDepartmentInsights: false,
  },
  [ROLES.OFFICE_SECRETARY]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: false,
    exportReports: true,
    editSundayPlanFull: false,
    viewDepartmentInsights: false,
  },
  [ROLES.VIEWER]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: false,
    exportReports: false,
    editSundayPlanFull: false,
    viewDepartmentInsights: false,
  },
}

export const DEPARTMENTS = [
  'Worship',
  'Cell Ministry',
  'Caring Department',
  'Sunday Ministry',
  'Junior Church',
  'Outreach',
  'Media',
  'Accounts',
  'Human Resources',
  'General Affairs',
  'Thunderstorm Youth',
  "ROL's School of Music",
  'RFF',
  'ROLF',
]

export const INCOME_TYPES = [
  'Offering 1',
  'Offering 2',
  'Offering 3',
  'Offering 4',
  'Offering 5',
  'Tithe',
  'Contribution',
  'RSM',
  'RFF',
  'Donations',
]

export const EXPENSE_CATEGORIES = [
  'Worship',
  'Cell Ministry',
  'Caring',
  'Sunday Ministry',
  'Junior Church',
  'Outreach',
  'Building',
  'Media',
  'Accounts',
  'Human Resources',
  'General Affairs',
  'Thunderstorm',
  'SP Office',
]

export const TASK_STATUS = {
  PENDING: 'Pending',
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
}

export const TASK_PRIORITY = ['Low', 'Medium', 'High', 'Urgent']

// Sunday Ministry Planning – sections (each department fills one)
export const SUNDAY_PLAN_SECTIONS = {
  SUNDAY_MINISTRY: 'sundayMinistry',
  WORSHIP: 'worship',
  SUNDAY_LEADER: 'sundayLeader',
  MEDIA: 'media',
  ANNOUNCEMENTS: 'announcements',
  D_LITE: 'dLite',
  RIVER_KIDS: 'riverKids',
}

// Roles that can edit a specific section only (same login, different view)
export const SECTION_ROLES = {
  'Sunday Ministry': SUNDAY_PLAN_SECTIONS.SUNDAY_MINISTRY,
  'Worship': SUNDAY_PLAN_SECTIONS.WORSHIP,
  'Media': SUNDAY_PLAN_SECTIONS.MEDIA,
  'D-Lite': SUNDAY_PLAN_SECTIONS.D_LITE,
  'River Kids': SUNDAY_PLAN_SECTIONS.RIVER_KIDS,
  'Announcements': SUNDAY_PLAN_SECTIONS.ANNOUNCEMENTS,
}
