export const ROLES = {
  FOUNDER: 'Founder',
  DIRECTOR: 'Director',
  ADMIN: 'Admin',
  FINANCE_TEAM: 'Finance Team',
  MINISTRY_LEADER: 'Ministry Leaders',
  VIEWER: 'Viewer',
}

export const ROLE_PERMISSIONS = {
  [ROLES.FOUNDER]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: true,
    manageDepartments: true,
    enterAttendance: true,
    enterFinance: true,
    exportReports: true,
  },
  [ROLES.DIRECTOR]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: false,
    exportReports: true,
  },
  [ROLES.ADMIN]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: false,
    reports: true,
    manageUsers: false,
    manageDepartments: true,
    enterAttendance: true,
    enterFinance: false,
    exportReports: true,
  },
  [ROLES.FINANCE_TEAM]: {
    dashboard: true,
    departments: false,
    tasks: false,
    attendance: false,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: true,
    exportReports: true,
  },
  [ROLES.MINISTRY_LEADER]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: false,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: true,
    enterFinance: false,
    exportReports: false,
  },
  [ROLES.VIEWER]: {
    dashboard: true,
    departments: true,
    tasks: true,
    attendance: true,
    finance: true,
    reports: true,
    manageUsers: false,
    manageDepartments: false,
    enterAttendance: false,
    enterFinance: false,
    exportReports: false,
  },
}

export const DEPARTMENTS = [
  'Worship',
  'Cell Ministry',
  'Caring Department',
  'Sunday Ministry',
  'Junior Church',
  'Outreach',
  'Media',
  'Accounts',
  'Human Resources',
  'General Affairs',
  'Thunderstorm Youth',
  "ROL's School of Music",
  'RFF',
  'ROLF',
]

export const INCOME_TYPES = [
  'Offering 1',
  'Offering 2',
  'Offering 3',
  'Offering 4',
  'Offering 5',
  'Tithe',
  'Contribution',
  'RSM',
  'RFF',
  'Donations',
]

export const EXPENSE_CATEGORIES = [
  'Worship',
  'Cell Ministry',
  'Caring',
  'Sunday Ministry',
  'Junior Church',
  'Outreach',
  'Building',
  'Media',
  'Accounts',
  'Human Resources',
  'General Affairs',
  'Thunderstorm',
  'SP Office',
]

export const TASK_STATUS = {
  PENDING: 'Pending',
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
}

export const TASK_PRIORITY = ['Low', 'Medium', 'High', 'Urgent']
